[package]
authors = ["Sam Gentle <sam@samgentle.com>"]
name = "bioupdater"
version = "0.2.0"

[dependencies]
hourglass = "0.6.4"
hyper = "0.7.2"
rand = "0.3.14"
rust-crypto = "0.2.34"
rustc-serialize = "0.3.18"
time = "0.1.34"
url = "0.5.5"
